name: Update Submodules

on: 
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # Fetch all history so we can push to the repo
        fetch-depth: 0
        submodules: true
